version: '3.9'

services:
  xssbot:
    build: .
    # shm_size: '1gb' # Uncomment if shared memory size needs to be set
    environment:
      COOKIE_DOMAIN: localhost
      COOKIE_KEY: flag
      COOKIE_VALUE: ctf{w0w_its_work1ng}
      BOT_PORT: 5000
    volumes:
      - ./scenario.js:/home/bot/scenario.js
    ports:
      - 8081:5000
    restart: always