version: "2"
services:
  xssbot:
    build: .
    # shm_size: '1gb'
    environment:
      - COOKIE_DOMAIN=localhost
      - COOKIE_KEY=flag
      - COOKIE_VALUE=ctf{w0w_its_work1ng}
      - BOT_PORT=5000
    restart: always